[package]
name = "opendb-operator"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "opendb-operator"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
