FROM debian:trixie-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*

COPY target/release/opendb-operator /usr/local/bin/opendb-operator

ENTRYPOINT ["/usr/local/bin/opendb-operator"]
